events {
    worker_connections 1024;
}

http {
    server {
        listen 127.0.0.1:8585;
        server_name _;

        location / {
            return 404;
            add_header Server "JULPONE NETWORK SERVER" always;
            add_header Alt-Svc "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000" always;
            add_header Cross-Origin-Resource-Policy "cross-origin" always;
        }
    }
}
